[package]
name = "assembler"
version = "0.2.1"
edition = "2024"

[dependencies]
isa = { workspace = true }
logger = { workspace = true }
regex = "1.11.2"
thiserror = { workspace = true }
args = { workspace = true }
