# .github/workflows/release.yml
name: Build and Release

# 1. Trigger this workflow when a new tag is pushed (e.g., v0.1.0)
on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-release:
    name: Build for ${{ matrix.os }}
    # 2. Run the job on three different operating systems
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      # 3. Checkout your repository's code
      - name: Checkout code
        uses: actions/checkout@v4

      # 4. Install the Rust toolchain
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      # 5. Build the executables in release mode
      - name: Build binaries
        run: cargo build --workspace --release --verbose

      # 6. Package the complete toolchain into one zip file per OS
      - name: Package Toolchain
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: 'compiler-toolchain-${{ github.ref_name }}-${{ runner.os }}.zip'
          directory: './target/release/'
          path: |
            cpu${{ runner.os == 'Windows' && '.exe' || '' }}
            assembler${{ runner.os == 'Windows' && '.exe' || '' }}
      
      # 7. Upload the single toolchain archive to the GitHub Release page
      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          # Give it the full path to where the zip file was created
          files: './target/release/compiler-toolchain-*.zip'